name: Build Prebuilt Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18, 20]
        
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Package prebuilt
        run: |
          mkdir -p prebuilds
          cp build/Release/*.node prebuilds/
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: prebuilds-${{ matrix.os }}-node${{ matrix.node }}
          path: prebuilds/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - uses: actions/checkout@v4
          
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Prepare release
        run: |
          mkdir -p prebuilds
          cp -r artifacts/*/* prebuilds/
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: prebuilds/*
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
