name: Build and upload binaries

on: workflow_dispatch

jobs:
  build:
    name: Build and upload

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install libsdl2-dev -y

      - if: ${{ matrix.os == 'macos-latest' }}
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install sdl2

      - if: ${{ matrix.os == 'windows-latest' }}
        run: |
          curl.exe https://www.libsdl.org/release/SDL2-devel-2.0.14-VC.zip -o SDL2.zip
          mkdir SDL2
          tar.exe -xf SDL2.zip -C SDL2 --strip 1
          del SDL2.zip

      - id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - run: npm install --no-save prebuild
      - run: npm run prebuild
      - run: npx prebuild --upload-all ${{ secrets.GITHUB_TOKEN }}
