name: Build and upload

on: workflow_dispatch

jobs:
  build:
    name: test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - run: npm i
        env:
          NODE_SDL_FROM_SOURCE: 1

      - run: node -e 'const sdl = require('.')'
