name: Test

on: workflow_dispatch

jobs:
  build:
    name: Test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - run: npm i

      - run: node -e 'const sdl = require('.')'
